### ISSUE TITLE
Dimensions in vec.npy

### ISSUE THREAD

**Issue by kh522** [thunlp/DocRED#7]
Hi, I was running the BiLSTM baselines as described in the README file, and I got an error:

Traceback (most recent call last):
  File "train.py", line 36, in <module>
    con.load_test_data()
  File "/kevin.huang/DocRED/code/config/Config.py", line 158, in load_test_data
    self.data_word_vec = np.load(os.path.join(self.data_path, 'vec.npy'))
  File "/kevin.huang/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/kevin.huang/anaconda3/lib/python3.6/site-packages/numpy/lib/format.py", line 734, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 3014533 into shape (194784,100)

Is the vec.npy file provided correct?

**Comment by YeDeming** [comment]
Metadata downloaded from may be ruined, you can try the [google drive link](https://drive.google.com/drive/folders/1Ri3LIILKKBi3aBJjUVCOBpGX5PpONHRK)
